---
title: "Portfolio"
description: |
  Some of my professional and personal work. 
output: 
  distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(htmltools)
# source("R/functions.R")
```


# Data visualizations
```{r eval=FALSE, include=FALSE}
create_proj_card(
  img_src = "images/here_say_media.png",
  url = "https://heresaymedia.org/chinatown-vaccine-rollout-lagging-rest-of-san-francisco/",
  title = "Vaccine Rollout in San Francisco Neighborhoods",
  text = "Data visualization and analysis for Here Say Media, 2021",
  text2 = ""
)
create_proj_card(
  img_src = "images/2021_04_hbcus.png",
  url = "https://github.com/Ijeamakaanyene/tidytuesday",
  title = "TidyTuesday",
  text = "A #R4DS Weekly Challenge. I am a regular contributor and all of my visualization are created solely using {ggplot2} and other extension packages, 2020",
  text2 = ""
)
create_proj_card(
  img_src = "https://raw.githubusercontent.com/mccoylab/covid_naturalhist_dataviz_2020/master/natural_history_infographic_v2.png",
  url = "https://ijeamaka-anyene.netlify.app/posts/2020-04-16-covid-19-visualization/",
  title = "COVID-19 Visualization",
  text = "An infectious disease natural history primer for U.C. Berkeley School of Public Health, 2020",
  text2 = ""
)
```
<br><br>

# Shiny apps
```{r eval=FALSE, include=FALSE}
create_proj_card(
  img_src = "images/logo.png",
  url = "https://ijeamaka-a.shinyapps.io/rtistry_gallery/",
  title = "rtistry art gallery",
  text = "A celebration and showcase of art in all of its forms created by the #rstats community. An entry for the RStudio 2021 Shiny Competition, 2021",
   text2 = "")

create_proj_card(
  img_src = "images/20210322212954.png",
  url = "https://github.com/Ijeamakaanyene/contouR",
  title = "{contouR}",
  text = "An R package for creating patterns using geom_contour(), 2021",
  text2 = "")
```